DROP TABLE IF EXISTS USERS;
CREATE TABLE  USERS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  USER_NAME VARCHAR(50),
  EMAIL VARCHAR(100),
  PASSWD VARCHAR(50),
  UNIQUE_ID VARCHAR(100) NOT NULL,
  VISITED_ON TIMESTAMP NOT NULL,
  REGISTERED SMALLINT DEFAULT 0,
  SHIPPING_ADDRESS_ID BIGINT,
  PAYMENT_METHOD BIGINT,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_USER_UNIQUE_ID ON USERS(UNIQUE_ID);
CREATE UNIQUE INDEX IDX_USER_UNIQUE_EMAIL ON USERS(EMAIL);
ALTER TABLE USERS ADD CONSTRAINT REF_USER_SHIPPING_ADDRESS FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESSES(ID);

DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ADDRESS_NAME VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	STREET VARCHAR(100) NOT NULL,
	ADDRESS_NUMBER VARCHAR(100) NOT NULL,
  	PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;

DROP TABLE IF EXISTS USER_ADDRESSES;
CREATE TABLE USER_ADDRESSES (
	USER_ID BIGINT NOT NULL,
	ADDRESS_ID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;
ALTER TABLE USER_ADDRESSES ADD CONSTRAINT REF_USER_ADDRESSES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE USER_ADDRESSES ADD CONSTRAINT REF_USER_ADDRESSES_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ID);

DROP TABLE IF EXISTS USER_CONFIRMATIONS;
CREATE TABLE USER_CONFIRMATIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  CODE VARCHAR(100) NOT NULL,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_USER_CONF_UNIQUE_CODE ON USER_CONFIRMATIONS(CODE);
CREATE UNIQUE INDEX IDX_USER_CONF_UNIQUE_USER ON USER_CONFIRMATIONS(USER_ID);

DROP TABLE IF EXISTS SHOP_INFO;
CREATE TABLE  SHOP_INFO (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ADDRESS_ID BIGINT NOT NULL,
  PERSON_NAME VARCHAR(50) NOT NULL,
  PERSON_SURNAME VARCHAR(50) NOT NULL,
  PHONE VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE SHOP_INFO ADD CONSTRAINT REF_SHOP_INFO_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ID);

DROP TABLE IF EXISTS SHOPS;
CREATE TABLE SHOPS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
  	SHOP_INFO_ID BIGINT DEFAULT NULL,
	NAME VARCHAR(50) NOT NULL,
  	IMAGE_SRC VARCHAR(50),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE SHOPS ADD CONSTRAINT REF_SHOP_INFO FOREIGN KEY (SHOP_INFO_ID) REFERENCES SHOP_INFO(ID);

DROP TABLE IF EXISTS MANAGERS;
CREATE TABLE MANAGERS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(50) NOT NULL,
  PASSWD VARCHAR(50) NOT NULL,
  SHOP_ID BIGINT NOT NULL,
  VISITED_ON TIMESTAMP NOT NULL,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE MANAGERS ADD CONSTRAINT REF_MANAGERS_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOPS(ID);

DROP TABLE IF EXISTS ITEMS;
CREATE TABLE ITEMS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SHOP_ID BIGINT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PRICE NUMERIC(10,2) NOT NULL,
  QUANTITY INTEGER NOT NULL,
  SHORT_DESCRIPTION VARCHAR(1000) NOT NULL,
  FULL_DESCRIPTION VARCHAR(10000) NOT NULL,
  IMAGE_SRC VARCHAR(50) NOT NULL,
  IS_ACTIVATED SMALLINT DEFAULT 1,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ITEMS ADD CONSTRAINT REF_ITEMS_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOPS(ID);

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
  	PARENT_ID BIGINT DEFAULT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE CATEGORIES ADD CONSTRAINT REF_CATEGORY FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES(ID);
CREATE UNIQUE INDEX IDX_CATEGORY_UNIQUE_NAME_PARENT ON CATEGORIES(NAME, PARENT_ID);

DROP TABLE IF EXISTS ITEM_CATEGORIES;
CREATE TABLE ITEM_CATEGORIES (
	CATEGORY_ID BIGINT NOT NULL,
	ITEM_ID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ITEM_CATEGORIES ADD CONSTRAINT REF_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID);
ALTER TABLE ITEM_CATEGORIES ADD CONSTRAINT REF_CATEGORY_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID);

DROP TABLE IF EXISTS CARTS;
CREATE TABLE CARTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_UNIQUE_CART_USER ON CARTS(USER_ID);
ALTER TABLE CARTS ADD CONSTRAINT REF_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

DROP TABLE IF EXISTS CART_ITEMS;
CREATE TABLE CART_ITEMS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CART_ID BIGINT NOT NULL,
  ITEM_ID BIGINT NOT NULL,
  ADDED_ON TIMESTAMP NOT NULL,
  QUANTITY BIGINT NOT NULL,
  PRIMARY KEY(ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE CART_ITEMS ADD CONSTRAINT REF_ITEM_IN_CART FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID);
ALTER TABLE CART_ITEMS ADD CONSTRAINT REF_CART FOREIGN KEY (CART_ID) REFERENCES CARTS(ID);

DROP TABLE IF EXISTS ADVERTISMENTS;
CREATE TABLE ADVERTISMENTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  LINK VARCHAR(200) NOT NULL,
  ITEM_ID BIGINT,
  SHOP_ID BIGINT,
  IMAGE_SRC VARCHAR(100),
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ADVERTISMENTS ADD CONSTRAINT REF_ADVERTISMENT_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID);
ALTER TABLE ADVERTISMENTS ADD CONSTRAINT REF_ADVERTISMENT_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(ID);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ITEM_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  COMMENTED_ON TIMESTAMP NOT NULL,
  CAPTION VARCHAR(200) NOT NULL,
  COMMENT VARCHAR(1000) NOT NULL,
  RATING BIGINT NOT NULL,
  VALUABLE_COUNT BIGINT NOT NULL,
  NOT_VALUABLE_COUNT BIGINT NOT NULL,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE COMMENTS ADD CONSTRAINT REF_COMMENT_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID);
ALTER TABLE COMMENTS ADD CONSTRAINT REF_COMMENT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

DROP TABLE IF EXISTS PROPERTIES;
CREATE TABLE PROPERTIES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PROPERTY_KEY VARCHAR(200) NOT NULL,
  PROPERTY_VALUE VARCHAR(200) NOT NULL,
  EXPLANATION VARCHAR(2000) NOT NULL,
  PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_UNIQUE_PROPERTY_KEY ON PROPERTIES(PROPERTY_KEY);

DROP TABLE IF EXISTS ATTRIBUTE_NAMES;
CREATE TABLE ATTRIBUTE_NAMES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(200) NOT NULL,
  	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_ATTRIBUTES_UNIQUE_ATTRIBUTE_CODE ON ATTRIBUTE_NAMES(CODE);

DROP TABLE IF EXISTS ATTRIBUTE_VALUES;
CREATE TABLE ATTRIBUTE_VALUES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CODE VARCHAR(200) NOT NULL,
	ATTRIBUTE_VALUE VARCHAR(200) NOT NULL,
	PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
CREATE UNIQUE INDEX IDX_ATTRIBUTES_UNIQUE_ATTRIBUTE_VALUE_CODE ON ATTRIBUTE_VALUES(CODE);

DROP TABLE IF EXISTS ATTRIBUTES;
CREATE TABLE ATTRIBUTES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ATTRIBUTE_NAME_ID BIGINT NOT NULL,
	ATTRIBUTE_VALUE_ID BIGINT NOT NULL,
  	PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ATTRIBUTES ADD CONSTRAINT REF_ATTRIBUTE_NAME FOREIGN KEY (ATTRIBUTE_NAME_ID) REFERENCES ATTRIBUTE_NAMES(ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT REF_ATTRIBUTE_VALUE FOREIGN KEY (ATTRIBUTE_VALUE_ID) REFERENCES ATTRIBUTE_VALUES(ID);
CREATE UNIQUE INDEX IDX_ATTRIBUTES_UNIQUE_ATTRIBUTE_NAME_VALUE ON ATTRIBUTES(ATTRIBUTE_NAME_ID, ATTRIBUTE_VALUE_ID);

DROP TABLE IF EXISTS ITEM_ATTRIBUTES;
CREATE TABLE ITEM_ATTRIBUTES (
	ITEM_ID BIGINT NOT NULL,
	ATTRIBUTE_ID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ITEM_ATTRIBUTES ADD CONSTRAINT REF_ATTRIBUTE_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID);
ALTER TABLE ITEM_ATTRIBUTES ADD CONSTRAINT REF_ATTRIBUTE FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTES(ID);
CREATE UNIQUE INDEX IDX_ATTRIBUTES_UNIQUE_ATTRIBUTE_ITEM ON ITEM_ATTRIBUTES(ITEM_ID, ATTRIBUTE_ID);

DROP TABLE IF EXISTS ATTRIBUTE_TEMPLATES;
CREATE TABLE ATTRIBUTE_TEMPLATES (
	CATEGORY_ID BIGINT NOT NULL,
	ATTRIBUTE_NAME_ID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ATTRIBUTE_TEMPLATES ADD CONSTRAINT REF_ATTRIBUTE_TEMPLATE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID);
ALTER TABLE ATTRIBUTE_TEMPLATES ADD CONSTRAINT REF_ATTRIBUTE_TEMPLATE_ATTRIBUTE_NAME FOREIGN KEY (ATTRIBUTE_NAME_ID) REFERENCES ATTRIBUTE_NAMES(ID);
CREATE UNIQUE INDEX IDX_ATTRIBUTE_TEMPLATES_UNIQUE_ATTRIBUTE_CATEGORY ON ATTRIBUTE_TEMPLATES(CATEGORY_ID, ATTRIBUTE_NAME_ID);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ORDERED_ON TIMESTAMP NOT NULL,
	USER_ID BIGINT NOT NULL,
	SHIPPING_ADDRESS_ID BIGINT NOT NULL,
	STATUS BIGINT NOT NULL,
	ORDER_PRICE NUMERIC(10,2) NOT NULL,
	DELIVERED_ON TIMESTAMP,
  	PRIMARY KEY  (ID)
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ORDERS ADD CONSTRAINT REF_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT REF_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

DROP TABLE IF EXISTS ORDER_ITEMS;
CREATE TABLE ORDER_ITEMS (
	ORDER_ID BIGINT NOT NULL,
	CART_ITEM_ID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT REF_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT REF_ORDER_ITEM FOREIGN KEY (CART_ITEM_ID) REFERENCES CART_ITEMS(ID);
